Repository byseif21/DEPI-E-Commerce-.NET-project, pull requests merged in 2025-05, with the labels that each got.

#5 factor: ongoing development of Home Page
  Views/Home/Index.cshtml
  Views/Shared/_Layout.cshtml
  wwwroot/asset/img/Fall.png
  wwwroot/css/home.css
Labels: Frontend

#6 factor: authentication pages layout
  Views/Account/ConfirmEmail.cshtml
  Views/Account/ForgotPassword.cshtml
  Views/Account/ForgotPasswordConfirmation.cshtml
  Views/Account/Lockout.cshtml
  Views/Account/Login.cshtml
  Views/Account/Register.cshtml
  Views/Account/ResetPassword.cshtml
  Views/Account/ResetPasswordConfirmation.cshtml
  Views/Shared/_Footer.cshtml
  Views/Shared/_Layout.cshtml
  Views/Shared/_LoginPartial.cshtml
  wwwroot/css/account.css
Labels: Frontend, Wafting for review

#7 factor: authentication backend
  Controllers/AccountController.cs
  Models/ForgotPasswordModel.cs
  Models/LoginModel.cs
  Models/RegisterModel.cs
  Models/ResetPasswordModel.cs
  Program.cs
  Services/EmailSender.cs
Labels: Backend

#8 factor: shop page
  Views/Products/Shop.cshtml
  wwwroot/css/shop.css
  wwwroot/js/shop.js
Labels: Frontend

#9 factor: the backend for the shop page
  Controllers/ProductsController.cs
  Models/Product.cs
  Models/ShopViewModel.cs
Labels: Backend

#10 fix: incomplete EF setup for authentication system
  Controllers/AccountController.cs
  Data/ApplicationDbContext.cs
  Program.cs
  Styleza.csproj
  Views/Account/Login.cshtml
  Views/Account/Register.cshtml
Labels: Frontend, Backend, Configuration

#14 feat: add loader to work across the site
  Views/Shared/_Layout.cshtml
  Views/Shared/_Loader.cshtml
  wwwroot/css/loader.css
  wwwroot/js/loader.js
Labels: Frontend

#15 factor: add mockup ecommerce data
  ecommerce_data/cartItems.xlsx
  ecommerce_data/carts.xlsx
  ecommerce_data/category.xlsx
  ecommerce_data/contactForm.xlsx
  ecommerce_data/order_items.xlsx
  ecommerce_data/orders.xlsx
  ecommerce_data/producr item.xlsx
  ecommerce_data/product configration.xlsx
  ecommerce_data/products.xlsx
  ecommerce_data/shipping method.xlsx
  ecommerce_data/shop_orders.xlsx
  ecommerce_data/shopping cart items.xlsx
  ecommerce_data/sub categories.xlsx
  ecommerce_data/users.xlsx
Labels: Backend
